"""Add audio fingerprint and similar songs fields

Revision ID: fa29c6fc90a4
Revises: 
Create Date: 2025-10-06 00:12:34.065520

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa29c6fc90a4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analysis_results', sa.Column('audio_fingerprint', sa.Text(), nullable=True))
    op.add_column('analysis_results', sa.Column('similar_songs', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('analysis_results', 'similar_songs')
    op.drop_column('analysis_results', 'audio_fingerprint')
    # ### end Alembic commands ###
